# Generated by Django 2.2.6 on 2019-11-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('buying', models.FloatField()),
                ('sales', models.FloatField()),
                ('diffrence', models.FloatField()),
                ('code', models.CharField(max_length=10)),
            ],
        ),
    ]
